### PR TITLE
Add linux doc build

### PR DESCRIPTION
**Pull request by jleonatti**
Move documentation build to Linux and remove Windows documentation build to address the legends issue in the example images. The doc package produced from the linux build has the legends showing properly:
image

### CODE REVIEW

**Comment by akaszynski** [comment]
I've removed the branch protection for the old doc build. We can enable it again one this PR is merged.

**Review by akaszynski — APPROVED** [review]
Nice work. LGTM.

**Review by cbellot000 — CHANGES_REQUESTED** [review]
Thanks @jleonatti for your work on that, but it seems that the API section is not working. I see that you are not using sphinx-apidoc as we did on windows, you can look [here](https://github.com/pyansys/pydpf-core/blob/master/.ci/build_doc.bat) for more details

**Comment by jleonatti** [comment]
> Merging can be performed automatically once the requested changes are addressed.

@cbellot000 thanks for pointing this out. I will fix it.

**Comment by jleonatti** [comment]
@cbellot000 looking at the doc package produced, I believe the API section is now working correctly. Please verify and let me know if there is anything else needed here!

**Review by cbellot000 — APPROVED** [review]

**Review by anslpa — APPROVED** [review]

**Pull request merged**
