### PR TITLE
Fix license issue in standalone

### PR DESCRIPTION
**Pull request by rafacanton**
Quick fix that solves the latest License Error

### CODE REVIEW

**Comment by PProfizi** [comment]
Hey @rafacanton, I think you might as well replace the modified lines with what is lines 37-39. This looks like forgotten duplication.

**Comment by anslpa** [comment]
> Hey @rafacanton, I think you might as well replace the modified lines with what is lines 37-39. This looks like forgotten duplication.

Hi @PProfizi, no this is probably not a duplication, it intends to create a fixture with entry servers, then reset the default context to premium 

@rafacanton

**Comment by PProfizi** [comment]
> > Hey @rafacanton, I think you might as well replace the modified lines with what is lines 37-39. This looks like forgotten duplication.
> 
> Hi @PProfizi, no this is probably not a duplication, it intends to create a fixture with entry servers, then reset the default context to premium
> 
> @rafacanton

Then I guess this is what is not working on the TFS side.

**Comment by rafacanton** [comment]
> > > Hey @rafacanton, I think you might as well replace the modified lines with what is lines 37-39. This looks like forgotten duplication.
> > 
> > 
> > Hi @PProfizi, no this is probably not a duplication, it intends to create a fixture with entry servers, then reset the default context to premium
> > @rafacanton
> 
> Then I guess this is what is not working on the TFS side.

@anslpa @PProfizi yes, the issue is deeper then.

**Pull request closed without merging**
