### PR TITLE
Improve doc generation

### PR DESCRIPTION
**Pull request by PProfizi**
Since implementing the strict success criterion on doc generation #491  (no example silently broken, no silent fail), the documentation generation job has proven to be extremely unstable, even more so the last few days.

This PR : 
- improves the logic when running examples via sphinx-gallery  
- fixes a few issues with the documentation
- fixes some doc build sphinx warnings
- implements the `clean` command in the documentations make.bat.

### CODE REVIEW

**Comment by PProfizi** [comment]
[ce9d569](https://github.com/pyansys/pydpf-core/pull/537/commits/ce9d569cddbf7e9165778042875677c10ba108c0) 
First try: OK

**Comment by PProfizi** [comment]
[f8afb5f](https://github.com/pyansys/pydpf-core/pull/537/commits/f8afb5ff95bfbf6ab7bca7605567457ec0f1b248) fails silently. Last line:
`generating gallery for examples\03-advanced... [ 50%] 03-exchange_data_between_servers.py`

**Comment by PProfizi** [comment]
Conclusion: the current changes proposed do stabilize the documentation generation, combined with several bug fixes implemented in the last few days. The problems persisting are under investigation in other specific PRs.

**Comment by cbellot000** [comment]
@PProfizi with the latest changes in master, I'm not having issues with the doc anymore, have you noticed some?

**Comment by PProfizi** [comment]
> @PProfizi with the latest changes in master, I'm not having issues with the doc anymore, have you noticed some?

@cbellot000, well you are right, the reason the doc was failing so much was examples failing due to bugs now fixed, yet this PR adds fail-safes to make sure that we detect failing examples correctly next time, and also adds the "kill servers" mechanic equivalent to what is done during testing. 

If you want I can rename the PR to "improving the documentation generation job".
I still think there are necessary/useful changes and fixes in the proposed modifications.

**Review by anslpa — APPROVED** [review]

**Pull request merged**
