### PR TITLE
cycles to failure example

### PR DESCRIPTION
**Pull request by mcMunich**
Simple example to demo using pydpf to generate a cycles to failure result.
1. simple solid model built/solved using pymapdl (files saved in c:/temp)
2. rst imported into pydpf
3. von mises stress extracted and plotted
4. numpy used to interpolate cycles to failure nodal results using von mises result and the imported steel cycles to failure material properties
5. cycles to failure result plotted to mesh and plot generated.

The goal of the example is a simple example to demo how a rst file can be used in python to generate a cycles to failure result.

### CODE REVIEW

**Comment by PProfizi** [comment]
Hey @mcMunich , I am sorry but right now our pipelines do not work for PRs from forks (as far as I understand the current problem). What I will do is replicate this PR myself directly from my cloned repo, and I will start an Issue regarding the acceptance of PRs from forks and what it entails, since it seems to be customary for pyMAPDL.

**Comment by PProfizi** [comment]
Posted an issue (#215) on accepting PRs from forks.
For now however I think only members with cloning rights can clone and push PRs for which the pipelines will run.

**Comment by mcMunich** [comment]
@PProfizi This is my first pull so I don't have any rights, as far as I can tell. 
I am one of the Ansys AEs in the European M-team who work with  pyansys. 
The example I am hoping to post is an interesting analysis that has been shown to a handfull of companies here in europe in a series of introducing pyansys talks.

**Comment by akaszynski** [comment]
@PProfizi, let's get this merged soon to avoid getting stale PRs.

If we need to, close this PR, create a branch directly from this repo, and recreate this PR to get the checks to pass. Be sure to give @mcMunich write permission to this repo.

This stems from the use of github secrets and our private use of the DPF binaries.

**Comment by rlagha** [comment]
Hi @mcMunich , I gave you write permissions to this repo, please could you create a branch instead of forking and create a PR from it? We planned to resolve the issue of running pipelines from the forks later.
@PProfizi , @akaszynski

**Comment by mcMunich** [comment]
sorry, pulled again but created a new branch and that one is the active one.

**Comment by PProfizi** [comment]
@mcMunich @akaszynski @rlagha @cbellot000 Indeed a new PR was made but still from the forked repository #223, so, as cleared-up in last week's pyAnsys meeting, it is not possible (nor desired) to make PRs from forked repositories with our current pipelines.
I started #224 and the last problem left is that the example actually runs MAPDL via pyMAPDL.
However, our doc pipeline runs the examples, so that would mean for our pipelines to install pyMAPDL.
I was discussing with Ramdane and the question becomes whether maybe this should be a pyMAPDL example, as it already installs and uses pyDPF. What do you think?

**Pull request closed without merging**
