### PR TITLE
fix ci and server versioning

### PR DESCRIPTION
**Pull request by cbellot000**

### CODE REVIEW

**Review by rlagha — APPROVED** [review]

**Comment by akaszynski** [comment]
Possible docbuild issue can be solved with:
https://stackoverflow.com/questions/55811545/importerror-cannot-load-backend-tkagg-which-requires-the-tk-interactive-fra

**Comment by cbellot000** [comment]
> Possible docbuild issue can be solved with:
> https://stackoverflow.com/questions/55811545/importerror-cannot-load-backend-tkagg-which-requires-the-tk-interactive-fra

**Comment by cbellot000** [comment]
Thanks @akaszynski, your fix for matplotlib worked!

**Comment by PProfizi** [comment]
Hi @cbellot000! Is this PR still active?

**Pull request closed without merging**
