### PR TITLE
custom title for mesh.plot(field)

### LINKED ISSUE #88: Changing plot title
I create a plot thanks to:
mesh = model.metadata.meshed_region
mesh.plot(my_field)
I'd like to change the title of this plot. I tried using the 'text' argument of the plot function of PyVista (https://docs.pyvista.org/api/plotting/_autosummary/pyvista.plot.html?highlight=mesh%20plot):
mesh.plot(my_field,text='dummy title')
But I get the following error:
image
Am I using this incorrectly? Not sure whether the issue is related to DPF-Core or to PyVista here.
Thanks!

### PR DESCRIPTION
**Pull request by TheGoldfish01**
Fixes #88 
Quick fix, adding recognition of "text" argument for simple custom title definition by adding text on the lower_edge using pyvista.Plotter.add_text
(NB: This is sort of a test)

### CODE REVIEW

**Comment by TheGoldfish01** [comment]
@rlagha  @cbellot000
Hello, sorry for the delay in trying my hand on actually making a draft pull request.
I took time this weekend to go through the documentation and the repositories, and started trying my hand on Github using a fork I made of the repository.
I chose this issue after discussing with Camille since it looked simple to try and make a quick fix and a small test.
Not sure if the tests are actually going to run for a draft request though.
This fix is in no mean meant to be comprehensive as a lot more should be done to actually call this a feature.
Since I am not yet aware of your strategy and requirements when making new features available, I kept to a simple dirty fix just to get used to the Github features.
I will keep looking at other Issues to try and help as well as learn.

**Comment by akaszynski** [comment]
I think the CI isn't going to run on ADO from an external branch. This is another reason to move over to GitHub Actions.

@rlagha, we can either copy these modifications and make our own PR with these change (with permission from @TheGoldfish01), or give him permission to push directly to the branch (i.e. write access). That's possible on a public repository.

**Comment by akaszynski** [comment]
@cbellot000, could you run this locally so we could validate this and merge? If we need to take another course of action (e.g. branch duplication) let's do it.

**Comment by cbellot000** [comment]
> @cbellot000, could you run this locally so we could validate this and merge? If we need to take another course of action (e.g. branch duplication) let's do it.

Sure, done here https://github.com/pyansys/pydpf-core/pull/134

**Comment by rlagha** [comment]
> > @cbellot000, could you run this locally so we could validate this and merge? If we need to take another course of action (e.g. branch duplication) let's do it.
> 
> Sure, done here #134
Thanks @TheGoldfish01 for the contribution, we appreciate.

Thanks @cbellot000  and @akaszynski for the process.

**Review by rlagha — APPROVED** [review]

**Comment by rlagha** [comment]
@akaszynski , the solution will be the Git Actions, we will add this into our plan.

**Pull request merged**
