### PR TITLE
Fix deprecation of numpy.float and numpy.int

### PR DESCRIPTION
**Pull request by anslpa**
Following this PR: https://github.com/pyansys/pydpf-core/pull/704/files

ansys-dpf-gate package tested with dpf-standalone branches:
[win_release-23.2_test_numpy](https://github.com/ansys-dpf/dpf-standalone/tree/win_release-23.2_test_numpy)
[linux_release-23.2_test_numpy](https://github.com/ansys-dpf/dpf-standalone/tree/linux_release-23.2_test_numpy)

Notes: 
- [x]  Standalone branches need to be merged into win_release-23.2 and linux_release-23.2 at the same time this one is merged.
- [x] .github/ansys_dpf_gate-0.3.1.dev0-py3-none-any.whl needs to be removed before merging (after it is published on Pypi).
- [ ] Update "Synchronize developments between pydpf-core (github) and TFS (server or python APIs packages).docx" file to explain the methodology to test an ansys-dpf-gate wheel (place in .github and in dpf-standalone)

### CODE REVIEW

**Comment by anslpa** [comment]
Running CI: https://github.com/pyansys/pydpf-core/actions/runs/3822193888

**Comment by anslpa** [comment]
Running CI: https://github.com/pyansys/pydpf-core/actions/runs/3823521544

**Comment by anslpa** [comment]
Running CI: https://github.com/pyansys/pydpf-core/actions/runs/3823886968

**Comment by anslpa** [comment]
Running CI: https://github.com/pyansys/pydpf-core/actions/workflows/ci.yml

**Comment by anslpa** [comment]
Running CI: https://github.com/pyansys/pydpf-core/actions/runs/3828084647/jobs/6513283068

**Comment by anslpa** [comment]
Running CI: https://github.com/pyansys/pydpf-core/actions/runs/3828136214

**Comment by PProfizi** [comment]
Passing CI : https://github.com/pyansys/pydpf-core/actions/runs/4014529970 --> OK

**Comment by PProfizi** [comment]
Running CI with newly released gate packages https://github.com/pyansys/pydpf-core/actions/runs/4251874317/jobs/7394771391

**Review by PProfizi — APPROVED** [review]

**Pull request merged**
