### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by PipKat**
This should NOT have been named patch-1. It should have been doc/edits_to_basic_examples. I entered that in the wrong field. Sorry.

Also, I couldn't remember where I left off editing so started back at the basics.

### CODE REVIEW

**Comment by PipKat** [comment]
@cbellot000 You approved this pull request but I can't merge it until the checks pass. Is there something you can do to get them to pass?

**Comment by cbellot000** [comment]
> @cbellot000 You approved this pull request but I can't merge it until the checks pass. Is there something you can do to get them to pass?

I think that you can pull master in your branch and push it on origin

**Comment by PipKat** [comment]
@akaszynski Camille provided a way of possibly getting this PR merged. However, I'm not sure I fully understand her suggestion and am looking for some help. Thanks!

**Comment by akaszynski** [comment]
I can help.  One moment.

**Comment by akaszynski** [comment]
Checks seem to be failing because the branch is external to this repository.  @PipKat, I can transfer this over if you're fine with that.

@cbellot000, this is another reason to eventually make our way to github actions.

**Comment by PipKat** [comment]
Please do! I don't know how I managed to screw this up. This is what happens when I'm off doing other traditional doc work for too long!

**Comment by PipKat** [comment]
This PR is being abandoned.

**Pull request closed without merging**
