### PR TITLE
mcMunichBranch

### PR DESCRIPTION
**Pull request by mcMunich**
okay, created a branch of my fork and now am pushing. Will be happy to speak english again afterwards.
In any case, there is a simple cycles to failure example in the basic examples folder that is self explanatory, hopefully.

### CODE REVIEW

**Comment by PProfizi** [comment]
Started an Issue (#225) regarding this.

**Comment by PProfizi** [comment]
Hi @mcMunich , sorry for it being so complicated to contribute, if you want we can discuss directly to clear-up the issue at hand.

**Review by mcMunich — COMMENTED** [review]
Added to beginning documentation to explain the script.

**Comment by PProfizi** [comment]
Hi @mcMunich, closing this PR as stale.

**Pull request closed without merging**
