### PR TITLE
Legends documentation issue

### PR DESCRIPTION
**Pull request by jleonatti**

### CODE REVIEW

**Comment by akaszynski** [comment]
Build failure was due to VTK==9.1.0, which was fixed on `master`.  I've merged with master and it seems to have solved the plotting issue.

**Comment by jleonatti** [comment]
@akaszynski After more testing, I see the same behavior when running the simple test on both ADO and Github Actions. 

When running this test script:

```
import pyvista
mesh = pyvista.Sphere()
mesh.plot(screenshot="tmp.png", scalars=range(mesh.n_points), off_screen=True)
```

On ADO, the screenshot produced is:
tmp

On Github, the screenshot produced is:
tmp

I will continue to investigate. Maybe it is due to the version of Windows for the build machines. I noticed that the documentation builds use "windows-2019".

**Comment by cbellot000** [comment]
@akaszynski, @jleonatti do you have an update on this issue?

**Comment by jleonatti** [comment]
> @akaszynski, @jleonatti do you have an update on this issue?

@cbellot000 I still have not been able to figure out what the issue is. I spoke with Alex about this and most other pyansys projects use Linux machines to build the documentation. It's possible that using Windows could be causing an issue for some reason. So, I was beginning to test out the documentation build running on a linux machine in #122.

**Comment by jleonatti** [comment]
Issue addressed in #122.

**Pull request closed without merging**
