### PR TITLE
Corrected wrong link for Scooby page in Pypi

### PR DESCRIPTION
**Pull request by jfthuong**

### CODE REVIEW

**Comment by rlagha** [comment]
hi @jfthuong , thanks for this fix, I'm correcting some issues related to the validation pipelines

**Comment by jfthuong** [comment]
@rlagha  Au plaisir.

**Comment by rlagha** [comment]
@jfthuong could you please update your branch with master and commit again? 
merci :)

**Comment by rlagha** [comment]
@jfthuong , the issue is due to the fork, please could you create a branch directly from master? We will work to fix the issue related to the forking.

**Comment by jfthuong** [comment]
@rlagha  I believe I don't have the write to work on a branch. ... but maybe I'm wrong? ;)

**Comment by akaszynski** [comment]
Reason why this is failing is we're not allowing secrets to be passed to forks. This is consistent with standard practices to avoid allowing external contributors to potentially steal secrets or tokens.

Since this PR is clearly fine and there's no reason why the checks should be failing, I'm just merging it.

**Comment by jfthuong** [comment]
Thanks Alex @akaszynski

**Pull request merged**
