### PR TITLE
Modernize project layout

### LINKED ISSUE #296: Update package layout to PyAnsys guidelines
As with other projects in the PyAnsys ecosystem, the layout of this project should adapt to the general guidelines.

## Low effort

- [ ] Enable Ruff rules
  - [ ] PyCodestyle
  - [x] PyDocstyle, see https://github.com/ansys/pydpf-core/pull/1975
  - [ ] PyFlakes, see https://github.com/ansys/pydpf-core/pull/1953
  - [x] Isort, see #2021 
  - [ ] PEP8-Naming
  - [x] Flake8-use-pathlib, see https://github.com/ansys/pydpf-core/pull/1949
  - [x] Flake8-todos, see https://github.com/ansys/pydpf-core/pull/1981

- [ ] Remove autoapi warning suppression once the codebase is healthier. See #1967 
- [x] Address removed reference labels from module docstrings. See #1980 

## Intermediate effort

- [x] Use a `src/` layout. Just need to move the "ansys/" dir inside a "src/" one and fix some links to this new location: #664

- [x] Use a `pyproject.toml` and drop any `setup.py` or `setup.cfg` files. https://github.com/ansys/pydpf-core/pull/909

- [x] Rename ``/docs`` directory to ``/doc``: Link issue here.

- [x] Implement Tox for the project
  - [x] Drop any patch scripts in favor of Tox 
    - #1989 
    - #2015 
    - #2031
    - #2056

- [x] Use sphinx-autoapi for generating the API reference, see https://github.com/ansys/pydpf-core/pull/1952
- [x] Improve static search live preview performance and fix missing module icons in the api documentation, see #1971 

## High effort

- [ ] Use containers from the GitHub Container Registry in the CI/CD
- [ ] Use semver tags

More about packaging guidelines in https://dev.docs.pyansys.com/packaging/structure.html.

### PR DESCRIPTION
**Pull request by jorgepiloto**
Resolves #296 by:

- [x] Moving from `setup.py` to `pyproject.toml`.
- [x] Collecting developer dependencies in a common `requirements/` directory.
- [x] Collect extra dependencies within `pyproject.toml`.
- [x] Move tools configuration to `pyproject.toml`.
- [x] Enable pre-commit for style checking.
- [ ] Updating `.github/` workflows to new layout.
- [ ] Protection rules for branch "main" must point to new actions

### CODE REVIEW

**Comment by jorgepiloto** [comment]
I just noticed that [scooby] is used for reporting. Shouldn't we use [ansys-report-tool]? Pinging here @PProfizi for having feedback on this question. Also, pinging @RobPasMue, as he is the main maintainer of [ansys-report-tool]. 

[scooby]: https://pypi.org/project/scooby/
[ansys-report-tool]: https://github.com/pyansys/pyansys-tools-report

**Comment by jorgepiloto** [comment]
> I just noticed that [scooby](https://pypi.org/project/scooby/) is used for reporting. Shouldn't we use [ansys-report-tool](https://github.com/pyansys/pyansys-tools-report)? Pinging here @PProfizi for having feedback on this question. Also, pinging @RobPasMue, as he is the main maintainer of [ansys-report-tool](https://github.com/pyansys/pyansys-tools-report).

Maybe the migration to ansys-tools-report can be made in a separate PR so this one does not get too complex.

**Comment by jorgepiloto** [comment]
Note: documentation is using the old PyAnsys logo.

**Comment by PProfizi** [comment]
> > I just noticed that [scooby](https://pypi.org/project/scooby/) is used for reporting. Shouldn't we use [ansys-report-tool](https://github.com/pyansys/pyansys-tools-report)? Pinging here @PProfizi for having feedback on this question. Also, pinging @RobPasMue, as he is the main maintainer of [ansys-report-tool](https://github.com/pyansys/pyansys-tools-report).
> 
> Maybe the migration to ansys-tools-report can be made in a separate PR so this one does not get too complex.

Hi @jorgepiloto, indeed this has been something to be done, a separate PR would be better.

**Comment by PProfizi** [comment]
> Note: documentation is using the old PyAnsys logo.

Hi @jorgepiloto, this is being modified [here ](https://github.com/pyansys/pydpf-core/pull/293)

**Comment by RobPasMue** [comment]
> > > I just noticed that [scooby](https://pypi.org/project/scooby/) is used for reporting. Shouldn't we use [ansys-report-tool](https://github.com/pyansys/pyansys-tools-report)? Pinging here @PProfizi for having feedback on this question. Also, pinging @RobPasMue, as he is the main maintainer of [ansys-report-tool](https://github.com/pyansys/pyansys-tools-report).
> > 
> > 
> > Maybe the migration to ansys-tools-report can be made in a separate PR so this one does not get too complex.
> 
> Hi @jorgepiloto, indeed this has been something to be done, a separate PR would be better.

Hi @jorgepiloto @PProfizi I can handle this in a new PR. Already done it for PyMAPDL :) See example: https://github.com/pyansys/pymapdl/pull/1215

**Comment by jorgepiloto** [comment]
I'm closing this after realizing that addressing so many changes in a single PR is going to be a drama for reviewers but also pretty complex to develop while other changes are being implemented.

**Pull request closed without merging**
