### PR TITLE
Fix 03-create_entities example

### PR DESCRIPTION
**Pull request by kmahajan-cadfem**
- fixed element_ids, previously it was only 1 for all elements
- changed naming from id -> n_id and e_id

### CODE REVIEW

**Comment by PProfizi** [comment]
Hello @kmahajan-cadfem, thank you for your contribution! 
Due to GitHub's [policy on secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow), validation workflows run for PRs from forked repositories will not work.
One solution to contribute is to clone the repository instead of forking it (despite forking being the best practice, as mentioned in our case it cannot work). Another is for me to replicate your proposed changes in a PR of my own.
As you prefer!

**Comment by kmahajan-cadfem** [comment]
@PProfizi,
Do you mean clone, create branch and then push? 
I have already tried this but could not create new remote branch!!

**Comment by PProfizi** [comment]
@kmahajan-cadfem, you are right, sorry, since write access are limited, not everyone can do that.
If you plan on contributing often I can check whether we could give you write access. If not, I will also ask the organization owners about the possibility to create a custom role that would make your contribution possible.
In the meantime I will simply prepare a PR with your suggestions and ping you.
Sorry about the confusion.

**Comment by kmahajan-cadfem** [comment]
@PProfizi 
for this change it does not make much sense to give me access, and you can go ahead.
as for the question, if i will be contributing regularly or not, I can not really answer you clearly because I also have other things to take care of and this is just by chance that I looked at the code and saw that there are some changes necessary.

I am still interested to know what are the options for DEVs(customers) to contribute?

**Comment by PProfizi** [comment]
> @PProfizi for this change it does not make much sense to give me access, and you can go ahead. as for the question, if i will be contributing regularly or not, I can not really answer you clearly because I also have other things to take care of and this is just by chance that I looked at the code and saw that there are some changes necessary.
> 
> I am still interested to know what are the options for DEVs(customers) to contribute?

Hi @kmahajan-cadfem well the options to contribute are : 
- to be registered as contributor with write access. 
- to open an enhancement issue with a description of the changes to be made, including possibly doing like you did wiith a PR from a fork as even though it will not get merged, one could still cherry-pick the commits on your fork branch to prepare an identical PR directly on the original repository.

**Comment by PProfizi** [comment]
For future reference, the equivalent PR is #550, closing this one.

**Comment by PProfizi** [comment]
Hi @kmahajan-cadfem, small change of plans. After discussing with colleagues managing the pyansys organisation, the conclusion was that to better give credit to external contributors, the process would be to create a mirror PR, run the checks there, then merge your PR by bypassing the required checks. This way we better keep track of contributors and give credit where due.
Again, sorry for the fuss, we are still settling the process concerning external contributions.

**Review by PProfizi — APPROVED** [review]

**Pull request merged**
